export const ActionTypes = {
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_SPOTS: "FETCH_SPOTS",
  FETCH_HEROS: "FETCH_HEROS",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_HEROS: "SET_HEROS",
  SET_SPOTS: "SET_SPOTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SELECTED_HERO: "SELECTED_HERO",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
};